# colorscheme
[[plugins]]
repo = 'overcache/NeoSolarized'

[[plugins]]
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'

# key bind
[[plugins]]
repo = 'houtsnip/vim-emacscommandline'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'mhinz/vim-signify'

# explore
[[plugins]]
repo = 'Shougo/defx.nvim'

# search
[[plugins]]
repo = 'Shougo/denite.nvim'

# lsp
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = '0'

